### ISSUE TITLE
error during startup in plugin.py

### ISSUE THREAD

**Issue by Markus-Be** [alturiak/nio-smith#19]
### Description:
Could not start the bot.

### Error:

> bin/python main.py 
> /home/markus/projekte/ebk/horscht/nio-smith/lib/python3.8/site-packages/fuzzywuzzy/fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
>   warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
> Traceback (most recent call last):
>   File "main.py", line 14, in <module>
>     from callbacks import Callbacks
>   File "/home/markus/projekte/ebk/horscht/nio-smith/callbacks.py", line 1, in <module>
>     from bot_commands import Command
>   File "/home/markus/projekte/ebk/horscht/nio-smith/bot_commands.py", line 1, in <module>
>     from pluginloader import PluginLoader
>   File "/home/markus/projekte/ebk/horscht/nio-smith/pluginloader.py", line 21, in <module>
>     from plugins import *
>   File "/home/markus/projekte/ebk/horscht/nio-smith/plugins/sampleplugin.py", line 148, in <module>
>     setup()
>   File "/home/markus/projekte/ebk/horscht/nio-smith/plugins/sampleplugin.py", line 21, in setup
>     plugin.add_config("default_message", "this is the default message", is_required=True)
>   File "/home/markus/projekte/ebk/horscht/nio-smith/plugin.py", line 330, in add_config
>     if self.configuration.get(config_item):
> AttributeError: 'bool' object has no attribute 'get'
> 

### How to reproduce:

1. git clone git@github.com:alturiak/nio-smith.git
2. cd nio-smith
3. python -m venv .
4. bin/pip install -r requirements.txt
5. mv sample.config.yaml config.yaml
6. bin/python main.py

### System:
OS: Manjaro 20.0.3
Python Version: 3.8.3
git commit: [c02d36ad72dfc8ad5a3f2b9a4afbeb5f118d79b3](https://github.com/alturiak/nio-smith/commit/c02d36ad72dfc8ad5a3f2b9a4afbeb5f118d79b3)

**Comment by alturiak** [comment]
@Markus-Be Thanks for the report, I did not handle missing plugin configuration files correctly. Should be fixed now.
