### ISSUE TITLE
Add installation instructions to the documentation

### ISSUE THREAD

**Issue by alturiak** [alturiak/nio-smith#22]

**Comment by dasTholo** [comment]
I´ve start to create a Dockerfile, docker-compose Installation script. But for now, i will run into a importerror.
More Information in the issue report at [nio-template](https://github.com/poljar/matrix-nio/issues/210)

When its done, i will write a installation document.

**Comment by Markus-Be** [comment]
I have added a short Installation instructions to the Readme

https://github.com/Eigenbaukombinat/nio-smith/commit/2810d9896264ed694be272024af100525770ae49
